CrudNet7Razor/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace CrudNet7Razor.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

CrudNet7Razor/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CrudNet7Razor.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

CrudNet7Razor/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CrudNet7Razor.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

CrudNet7Razor/Pages/Productos/Crear.cshtml.cs
using CrudNet7Razor.Datos;
using CrudNet7Razor.Modelos;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CrudNet7Razor.Pages.Productos
{
    public class CrearModel : PageModel
    {
        private readonly ApplicationDbContext _contexto;

        public CrearModel(ApplicationDbContext contexto)
        {
            _contexto = contexto;
        }

        [BindProperty]
        public Producto Producto { get; set; }

        [TempData]
        public string Mensaje { get; set; }


        public void OnGet()
        {
        }

        public async Task<IActionResult> OnPost()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            Producto.FechaCreacion = DateTime.Now;

            _contexto.Add(Producto);
            await _contexto.SaveChangesAsync();
            Mensaje = "Producto creado correctamente";
            return RedirectToPage("Index");
        }
    }
}

CrudNet7Razor/Pages/Productos/Editar.cshtml.cs
using CrudNet7Razor.Datos;
using CrudNet7Razor.Modelos;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CrudNet7Razor.Pages.Productos
{
    public class EditarModel : PageModel
    {
        private readonly ApplicationDbContext _contexto;

        public EditarModel(ApplicationDbContext contexto)
        {
            _contexto = contexto;
        }

        [BindProperty]
        public Producto Producto { get; set; }

        [TempData]
        public string Mensaje { get; set; }

        public async Task OnGet(int id)
        {
            Producto = await _contexto.Producto.FindAsync(id);
        }

        public async Task<IActionResult> OnPost()
        {
            if (ModelState.IsValid)
            {
                var CursoDesdeDB = await _contexto.Producto.FindAsync(Producto.Id);

                CursoDesdeDB.NombreProducto = Producto.NombreProducto;
                CursoDesdeDB.Descripcion = Producto.Descripcion;
                CursoDesdeDB.EnStock = Producto.EnStock;
                CursoDesdeDB.Precio = Producto.Precio;

                await _contexto.SaveChangesAsync();
                Mensaje = "Producto editado correctamente";
                return RedirectToPage("Index");
            }

            return RedirectToPage();
            
        }
    }
}

CrudNet7Razor/Pages/Productos/Index.cshtml.cs
using CrudNet7Razor.Datos;
using CrudNet7Razor.Modelos;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace CrudNet7Razor.Pages.Productos
{
    public class IndexModel : PageModel
    {
        private readonly ApplicationDbContext _contexto;

        public IndexModel(ApplicationDbContext contexto)
        {
            _contexto = contexto;
        }

        public IEnumerable<Producto> Productos { get; set; }

        [TempData]
        public string Mensaje { get; set; }

        public async Task OnGet()
        {
            Productos = await _contexto.Producto.ToListAsync();
        }

        public async Task<IActionResult> OnPostBorrar(int id)
        {
            var producto = await _contexto.Producto.FindAsync(id);
            if (producto == null)
            {
                return NotFound();
            }

            _contexto.Producto.Remove(producto);
            await _contexto.SaveChangesAsync();
            Mensaje = "Producto borrado correctamente";
            return RedirectToPage("Index");
        }
    }
}

CrudNet7Razor/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

CrudNet7Razor/Pages/Productos/Crear.cshtml
@page
@model CrudNet7Razor.Pages.Productos.CrearModel
@{
    ViewData["Title"] = "Crear nuevo producto";
}

<h3 class="text-center">Mira nuestros cursos profesionales en:<a href="https://softdevelopp.com" target="_blank"> www.softdevelopp.com</a></h3>

<div class="card">
    <div class="card-header bg-dark">
           <h2 class="text-info">Crear un nuevo producto</h2>
    </div>

    <div class="card-body">
        <form method="POST">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="container" style="padding:30px">
                <div class="form-group">
                    <div class="row">
                        <div class="col-sm-2">
                            <label asp-for="Producto.NombreProducto"></label>
                        </div>
                         <div class="col-sm-6">
                            <input asp-for="Producto.NombreProducto" class="form-control"/>
                        </div>
                        <span asp-validation-for="Producto.NombreProducto" class="text-danger"></span>
                    </div>
                </div>

                 <div class="form-group">
                    <div class="row">
                        <div class="col-sm-2">
                            <label asp-for="Producto.Descripcion"></label>
                        </div>
                         <div class="col-sm-6">
                            <input asp-for="Producto.Descripcion" class="form-control"/>
                        </div>
                        <span asp-validation-for="Producto.Descripcion" class="text-danger"></span>
                    </div>
                </div>

                 <div class="form-group">
                    <div class="row">
                        <div class="col-sm-2">
                            <label asp-for="Producto.EnStock"></label>
                        </div>
                         <div class="col-sm-6">
                            <input asp-for="Producto.EnStock" class="form-control"/>
                        </div>
                        <span asp-validation-for="Producto.EnStock" class="text-danger"></span>
                    </div>
                </div>

                 <div class="form-group">
                    <div class="row">
                        <div class="col-sm-2">
                            <label asp-for="Producto.Precio"></label>
                        </div>
                         <div class="col-sm-6">
                            <input asp-for="Producto.Precio" class="form-control"/>
                        </div>
                        <span asp-validation-for="Producto.Precio" class="text-danger"></span>
                    </div>
                </div>

                 <div class="form-group mt-4">
                    <div class="row">
                        <div class="col-sm-2 offset-sm-2">
                           <input type="submit" value="Crear" class="btn btn-primary form-control" />
                        </div>
                         <div class="col-sm-4">
                            <a asp-page="Index" class="btn btn-success form-control">Volver a lista</a>
                        </div>                       
                    </div>
                </div>
            </div>
        </form>
    </div>

</div>

CrudNet7Razor/Pages/Productos/Editar.cshtml
@page
@model CrudNet7Razor.Pages.Productos.EditarModel
@{
    ViewData["Title"] = "Editar producto";
}

<h3 class="text-center">Mira nuestros cursos profesionales en:<a href="https://softdevelopp.com" target="_blank"> www.softdevelopp.com</a></h3>

<div class="card">
    <div class="card-header bg-dark">
        <h2 class="text-info">Editar producto</h2>
    </div>

    <div class="card-body">
        <form method="POST">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <!--Se envia el id como campo oculto-->
            <input type="hidden" asp-for="Producto.Id" />

            <div class="container" style="padding:30px">
                <div class="form-group">
                    <div class="row">
                        <div class="col-sm-2">
                            <label asp-for="Producto.NombreProducto"></label>
                        </div>
                        <div class="col-sm-6">
                            <input asp-for="Producto.NombreProducto" class="form-control" />
                        </div>
                        <span asp-validation-for="Producto.NombreProducto" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-group">
                    <div class="row">
                        <div class="col-sm-2">
                            <label asp-for="Producto.Descripcion"></label>
                        </div>
                        <div class="col-sm-6">
                            <input asp-for="Producto.Descripcion" class="form-control" />
                        </div>
                        <span asp-validation-for="Producto.Descripcion" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-group">
                    <div class="row">
                        <div class="col-sm-2">
                            <label asp-for="Producto.EnStock"></label>
                        </div>
                        <div class="col-sm-6">
                            <input asp-for="Producto.EnStock" class="form-control" />
                        </div>
                        <span asp-validation-for="Producto.EnStock" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-group">
                    <div class="row">
                        <div class="col-sm-2">
                            <label asp-for="Producto.Precio"></label>
                        </div>
                        <div class="col-sm-6">
                            <input asp-for="Producto.Precio" class="form-control" />
                        </div>
                        <span asp-validation-for="Producto.Precio" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-group mt-4">
                    <div class="row">
                        <div class="col-sm-2 offset-sm-2">
                            <input type="submit" value="Editar" class="btn btn-primary form-control" />
                        </div>
                        <div class="col-sm-4">
                            <a asp-page="Index" class="btn btn-success form-control">Volver a lista</a>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>

</div>

CrudNet7Razor/Pages/Productos/Index.cshtml
@page
@model CrudNet7Razor.Pages.Productos.IndexModel
@{
    ViewData["Title"] = "Lista de productos";
}

<h3 class="text-center">Mira nuestros cursos profesionales en:<a href="https://softdevelopp.com" target="_blank"> www.softdevelopp.com</a></h3>

@if (Model.Mensaje != null)
{
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        @Model.Mensaje
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
}


<div class="card">
    <div class="card-header bg-dark">
        <div class="row">
            <div class="col-sm-9">
                <h2 class="text-info">Lista de productos</h2>
            </div>
             <div class="col-sm-3">
               <a asp-page="Crear" class="btn btn-primary">Crear Nuevo Producto</a>
            </div>
        </div>
    </div>
    
    <div class="card-body">
        <form method="POST">
        @if (Model.Productos.Count() > 0)
        {
            <br />
            <table class="table table-striped border">
                <tr class="table-secondary">
                    <th>@Html.DisplayNameFor(m => m.Productos.First().Id)</th>
                    <th>@Html.DisplayNameFor(m => m.Productos.First().NombreProducto)</th>
                    <th>@Html.DisplayNameFor(m => m.Productos.First().Descripcion)</th>
                    <th>@Html.DisplayNameFor(m => m.Productos.First().EnStock)</th>
                    <th>@Html.DisplayNameFor(m => m.Productos.First().Precio)</th>
                    <th>@Html.DisplayNameFor(m => m.Productos.First().FechaCreacion)</th>
                    <th>Acciones</th>
                </tr>
                @foreach (var item in Model.Productos)
                {
                   <tr>
                        <td>@Html.DisplayFor(m => item.Id)</td>
                        <td>@Html.DisplayFor(m => item.NombreProducto)</td>
                        <td>@Html.DisplayFor(m => item.Descripcion)</td>
                        <td>@Html.DisplayFor(m => item.EnStock)</td>
                        <td>@Html.DisplayFor(m => item.Precio)</td>
                        <td>@Html.DisplayFor(m => item.FechaCreacion)</td>
                        <td>
                            <a asp-route-id="@item.Id" asp-page="Editar" class="btn btn-success btn-sm">Editar</a>
                            <button asp-page-handler="Borrar" asp-route-id="@item.Id" onclick="return confirm('Esta seguro de querer borrar el producto?')" class="btn btn-danger btn-sm">Borrar</button>
                        </td>
                   </tr>
                }
            </table>
        }
        else
        {
            <p>No hay productos disponibles</p>
        }
       </form>
    </div>
</div>

CrudNet7Razor/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CrudNet7Razor</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CrudNet7Razor.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">CrudNet7Razor</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-page="/Index">Inicio</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-page="/Productos/Index">Administración de Productos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - CrudNet7Razor - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>